image: openjdk:11

stages:
    - build
    - test
    
perftest_builder:
    stage: build
    script:
        - "javac -cp src/ -d out src/Main.java"
    artifacts:
        paths:
            - "src/Snakeblock.class"
            - "src/Apple.class"
            - "src/Game.class"
            - "src/Main.class"
            - "src/MainMenu.class"
            
perftest_validator:
    stage: test
    before_script:
        - "javac -cp src/ -d out src/Main.java"
    script:
        - "java -cp out src.Main"
