stages:
    - build
    - test
    
build:
    stage: build
    script:
        - javac Main.java
    artifacts:
        paths:
            - Main.class
            
test:
    stage: execute
    script: 
        - java Main