image: openjdk:11

stages:
    - build
    - execute
    
build:
    stage: build
    script:
        - "javac src/Game.java"
        - "javac src/Snakeblock.java"
        - "javac src/Apple.java"
        - "javac src/Main.java"
        - "javac src/MainMenu.java"

    artifacts:
        paths:
            - "bin/Snakeblock.class"
            - "bin/Apple.class"
            - "bin/Game.class"
            - "bin/Main.class"
            - "bin/MainMenu.class"
            
execute:
    stage: excecute
    script:
        - "java src/Main"