image: java:latest

stages:
    - build

    
perftest_builder:
    stage: build
    script:
        - "javac src/Snakeblock.java"
        - "javac src/Apple.java"
        - "javac src/Game.java"
        - "javac src/Main.java"
        - "javac src/MainMenu.java"

    artifacts:
        paths:
            - "src/Snakeblock.*"
            - "src/Apple.*"
            - "src/Game.*"
            - "src/Main.*"
            - "src/MainMenu.*"
            
