image: openjdk:11

stages:
    - build
    - test
    
perftest_builder:
    stage: build
    script:
         - "javac src/Main.java"
    artifacts:
        paths:
            - "src/Main.class"
            
perftest_validator:
    stage: test
    before_script:
        - "javac src/Main.java"
    script:
        - "java src.Main"