image: java:latest

stages:
    - build

    
perftest_builder:
    stage: build
    script:
        - "javac src/Snakeblock.java"
        - "javac src/Apple.java"
        - "javac src/Game.java"
        - "javac src/Main.java"
        - "javac src/MainMenu.java"

    artifacts:
        paths:
            - "src/Snakeblock.class"
            - "src/Apple.class"
            - "src/Game.class"
            - "src/Main.class"
            - "src/MainMenu.class"
            
