image: java:latest

stages:
    - build
    - excecute
    
build:
    stage: build
    script: javac src/Main.java
    artifacts:
        paths:
            - Main.*
            
execute:
    stage: execute
    script: java src/Main