image: openjdk:11

stages:
    - build
    
perftest_builder:
    stage: build
    script:
        - "javac -cp src/ -d out src/Main.java"
    artifacts:
        paths:
            - "src/Snakeblock.class"
            - "src/Apple.class"
            - "src/Game.class"
            - "src/Main.class"
            - "src/MainMenu.class"
            

